### ISSUE TITLE
Speech AsyncRecognizeMetadata progressPercent is always 0

### ISSUE THREAD

**Issue by srubin** [GoogleCloudPlatform/google-cloud-node#1875]
After creating an async speech recognition operation, the `progressPercent` of the [AsyncRecognizeMetadata](https://cloud.google.com/speech/reference/rpc/google.cloud.speech.v1beta1#google.cloud.speech.v1beta1.AsyncRecognizeMetadata) (when listening to the `progress` event) is always 0. It's supposed to be range from 0 to 100.

#### Environment details

  - OS: macOS 10.12.2 Beta (16C48b)
  - Node.js version: v6.4.0
  - npm version: 3.10.3
  - google-cloud-node version: `"@google-cloud/speech": "^0.5.0"`

#### Steps to reproduce

1. `$ wget https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/master/speech/resources/audio2.raw?raw=true -O audio2.raw`
2. Create test file progressPercentBug.js:
```js
var speech = require('@google-cloud/speech')();

const config = {
  encoding: 'LINEAR16',
  sampleRate: 16000
};

speech.startRecognition('audio2.raw', config, (err, operation) => {
  if (err) {
    return;
  }

  operation
    .on('progress', (progress) => {
      console.log("progress")
      console.log(progress)
    })
    .on('complete', (result) => {
      console.log("result")
      console.log(result)
    })
    .on('error', (err) => {
      console.log("error")
      console.log(err)
    })
})
```
3. `$ GCLOUD_PROJECT= GOOGLE_APPLICATION_CREDENTIALS= node progressPercentBug` and the output will be, roughly:

```
progress
{ progressPercent: 0,
  startTime:
   { seconds: Long { low: 1481320685, high: 0, unsigned: false },
     nanos: 843408000 },
  lastUpdateTime:
   { seconds: Long { low: 1481320686, high: 0, unsigned: false },
     nanos: 97801000 } }
progress
{ progressPercent: 0,
  startTime:
   { seconds: Long { low: 1481320685, high: 0, unsigned: false },
     nanos: 843408000 },
  lastUpdateTime:
   { seconds: Long { low: 1481320686, high: 0, unsigned: false },
     nanos: 97801000 } }
...
```

**Comment by jmuk** [comment]
@landrito do you observe this behavior?

**Comment by landrito** [comment]
I'll look into this.

**Comment by landrito** [comment]
Found the problem. It seems the check to see if the metadata value has changed was using the wrong operation. With this change the progress will only be emitted on an update to the metadata.

**Comment by stephenplusplus** [comment]
This is fixed if you install `@google-cloud/speech` directly. The fix will be included in our next `google-cloud` release as well. Thanks for catching this!

**Comment by srubin** [comment]
Thanks for the quick fix!

**Comment by landrito** [comment]
NP!

**Comment by srubin** [comment]
I'm not getting duplicate progress messages anymore, per this fix, but I'm still not getting particularly useful progress information. When I add a log statement `console.log(metadata)` at `longrunning.js:298` I see a bunch of metadata with `progressPercent == 0` and then one final piece of metadata with `progressPercent == 100`. I don't know if this is a bug or if the Cloud Speech API simply doesn't give real progress updates. Any info on this, @landrito?

**Comment by srubin** [comment]
Actually, I'm seeing progress updates for longer files. For example, when I transcribe a fifteen minute long file, I'm getting progress updates roughly every 10-15% (0%, 11%, 23%, 41%, 53%, ...).
