### ISSUE TITLE
Cloud Spanner: Session being deleted and created on each call

### ISSUE THREAD

**Issue by vkedia** [GoogleCloudPlatform/google-cloud-node#2685]
A customer reported seeing higher latencies on ExecuteStreamingSql. Debugging further they realised that after every ExecuteStreamingSql call, a DeleteSession and CreateSession is being called which is unexpected.
This is the information from customer:

Our App is currently deployed with-in GCP in a Docker container running Node V8 and we are using Spanner module 0.7.1
When establishing a connection to Spanner we are using a singleton pattern where we retain a global reference to the spanner, instance and database objects returned by the Spanner API.
 
When requesting the database connection from the spanner instance, we are using the following connection options:

```es6
database = spannerInstance.database(‘database’, {min: 20, keepAlive: 10});
```

After we enabled Google Stackdriver Trace we noticed that on essentially every request made to our deployed service that involved the execution of a Spanner query:

```es6
database.run(‘select stuff from table thing where column = value’).then(results => {
  …do stuff…
}).catch(err=>{
  ..uh oh..
});
 ```

That we see the following gRPC time spans logged in the following order:
```
grpc:/google.spanner.v1.Spanner/ExecuteStreamingSql
grpc:/google.spanner.v1.Spanner/DeleteSession
grpc:/google.spanner.v1.Spanner/CreateSession
```

**Comment by vkedia** [comment]
cc @lukesneeringer

**Comment by lukesneeringer** [comment]
@vkedia Can you describe the expected behavior? (In other words, when do you assert the sessions should be created and deleted?)

**Comment by vkedia** [comment]
Session deletion should always happen asynchronously in the background. Session creation can possibly happen inline. But the main point is at most 100 sessions should be created (since that is the default value for maximum sessions). After that those sessions should be reused. Number of sessions being created should be much lower than the number of read/query/write rpcs made. From the backend log that does not seem to be the case. It seems as if one session is created and deleted for every rpc being made which defeats the purpose of a session pool.

**Comment by callmehiphop** [comment]
@vkedia this is a small configuration bug, there's a code freeze on Spanner while we migrate it to a new repository, but in the mean time you can tell users to set `maxIdle` to the same value as `min` (or higher)

**Comment by vkedia** [comment]
So if `maxIdle` is 0 a session gets closed everytime it is returned to the pool?

**Comment by vkedia** [comment]
Can they set it to be the same as `max` so basically set it to 100?

**Comment by callmehiphop** [comment]
> So if maxIdle is 0 a session gets closed everytime it is returned to the pool?

Yep :/

> Can they set it to be the same as max so basically set it to 100?

Yep! For the work around if it is not set, my plan was just to set it to the same value as `min` and if that's not set, set it to `1`. Basically we just want it to be higher than the `min` value.

**Comment by vkedia** [comment]
Can you point me to the documentation of maxIdle in the third party pooling library you are using? I would like to understand its semantics in bit more details.

**Comment by callmehiphop** [comment]
Actually it's a feature we implemented per [your request](https://github.com/GoogleCloudPlatform/google-cloud-node-private/pull/12#issuecomment-267658663). I think we just didn't factor in using `min` as a base value.

**Comment by vkedia** [comment]
Yeah I know it was implemented as per the requirements. But the session being closed was not an idle session. It was just now in use. So even if you don't account for min, it should not be closed? How do you determine how many sessions were idle?

**Comment by callmehiphop** [comment]
We basically just treated anything not currently being used as an idle session, so even though that particular session was being used, once it was released it was considered idle again. Should we have some sort of configurable timeout that marks it idle?

**Comment by vkedia** [comment]
Yeah we should have a timeout to mark it idle. The timeout can be 10 minutes and need not be configurable. One challenge around this is depending on how the pooling library checks out sessions, every session would likely get used at least once in 10 minutes even though actual number of sessions needed might be lower. For eg if the pooling library maintains a queue of sessions and say the queue has 10 sessions right now. Even if the user is just making 1 rpc at a time, they will end up using all the sessions one after the another in short while so we will not consider any of them as idle.
To get around this, what can be done is maintain a count of number of sessions that have been checked out at any point in time. Maximum value for this counter over last 10 minutes will tell you how many sessions you actually need. Any more than that can be considered idle and closed down.

**Comment by vkedia** [comment]
This is not completely resolved. As per my last comment, I think the bigger issue is how a session is determined to be idle. That also needs to be fixed. @lukesneeringer can you reopen this?

**Comment by lukesneeringer** [comment]
Yeah.

**Comment by lukesneeringer** [comment]
This issue was moved to googleapis/nodejs-spanner#25
